---
title: "Jonathan Chan"
---

Hi! I'm Jonathan Chan, a graduate student in the MS in Artificial Intelligence and Business Analytics program at Baruch College.

I'm interested in data science, machine learning, analytics, and using data to solve real-world problems. My current interests include healthcare analytics, public-sector analytics, and financial services.

This website contains my work for STA 9750: Applied Statistics for Analytics.

## About Me

I have experience working with Python, R, SQL, machine learning, data visualization, and large datasets.

Some of my recent projects include analyzing NYC 311 service request data, building machine learning models, and developing data-driven applications.

I also did a GenAI hackathon sponsored by Capital One where I made an app that translated difficult documents into simpler language and different languages

Work in progress obv but I want to put my conferences, club exp, work exp, projects, and what i do for fun

## STA 9750

This site will contain my mini-projects and course project for STA 9750.
```{r}
#| include: false

1 + 1
```

---

Last Updated: `r format(Sys.time(), "%A %m %d, %Y at %H:%M%p")`